
export const timezones = [
  { value: 'America/New_York', label: 'Eastern Time (US & Canada)' },
  { value: 'America/Chicago', label: 'Central Time (US & Canada)' },
  { value: 'America/Denver', label: 'Mountain Time (US & Canada)' },
  { value: 'America/Los_Angeles', label: 'Pacific Time (US & Canada)' },
  { value: 'America/Anchorage', label: 'Alaska (US)' },
  { value: 'Pacific/Honolulu', label: 'Hawaii (US)' },
  { value: 'America/Toronto', label: 'Eastern Time (Canada)' },
  { value: 'America/Vancouver', label: 'Pacific Time (Canada)' },
  { value: 'Europe/London', label: 'London, Edinburgh (UK)' },
  { value: 'Europe/Paris', label: 'Paris, Berlin, Rome, Madrid' },
  { value: 'Europe/Moscow', label: 'Moscow, St. Petersburg' },
  { value: 'Asia/Tokyo', label: 'Tokyo, Osaka' },
  { value: 'Asia/Shanghai', label: 'Beijing, Shanghai' },
  { value: 'Asia/Singapore', label: 'Singapore, Malaysia' },
  { value: 'Asia/Dubai', label: 'Dubai, Abu Dhabi' },
  { value: 'Asia/Kolkata', label: 'Mumbai, New Delhi' },
  { value: 'Australia/Sydney', label: 'Sydney, Melbourne' },
  { value: 'Pacific/Auckland', label: 'Auckland, Wellington' },
  { value: 'Africa/Lagos', label: 'Lagos, Kano' },
  { value: 'Africa/Nairobi', label: 'Nairobi, Mombasa' },
  { value: 'Africa/Cairo', label: 'Cairo, Alexandria' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg, Cape Town' },
  { value: 'America/Sao_Paulo', label: 'São Paulo, Rio de Janeiro' },
  { value: 'America/Mexico_City', label: 'Mexico City' }
];
